services:
  # ✅ Database Bản Sao (Read Replica)
  db_slave:
    image: mariadb:latest
    container_name: smartlms-db-slave
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    mem_limit: 300m
    command: >
      --server-id=2
      --log-bin=mysql-bin
      --binlog-format=ROW
      --slave-skip-errors=1062,1032
      --innodb-buffer-pool-size=64M
      --innodb-log-file-size=128M
      --max-connections=5000
    networks:
      - smartlms-worker-net

  backend:
    image: ghcr.io/jacksama11223/asp.net-app/smartlms-backend:latest
    restart: always
    mem_limit: 250m
    deploy:
      replicas: 3
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      # ✅ Ghi dữ liệu: Kết nối về VPS-A (Master) qua mạng Internet
      - ConnectionStrings__DefaultConnection=Server=YOUR_VPS_IP;Port=3306;Database=SmartLMS;User=root;Password=${DB_PASSWORD};SslMode=None;Maximum Pool Size=30;Connection Timeout=300;Command Timeout=300;
      # ✅ Đọc dữ liệu: Kết nối về VPS-B (Slave) qua Localhost siêu tốc
      - ConnectionStrings__ReadOnlyConnection=Server=db_slave;Port=3306;Database=SmartLMS;User=root;Password=${DB_PASSWORD};SslMode=None;Maximum Pool Size=100;Connection Timeout=300;Command Timeout=300;
      - Redis__ConnectionString=YOUR_VPS_IP:6379,password=YOUR_REDIS_PASSWORD_HERE
      - COMPlus_gcServer=0
      - DOTNET_GCConserveMemory=9
      - DOTNET_GCHeapHardLimitPercent=75
    ports:
      - "5381-5383:8080"
    networks:
      - smartlms-worker-net

  frontend-community:
    image: ghcr.io/jacksama11223/asp.net-app/smartlms-frontend:latest
    container_name: smartlms-frontend-community
    restart: always
    mem_limit: 30m
    ports:
      - "5182:80"
    networks:
      - smartlms-worker-net

  community:
    image: ghcr.io/jacksama11223/asp.net-app/smartlms-community:latest
    restart: always
    mem_limit: 200m
    deploy:
      replicas: 1
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=YOUR_VPS_IP;Port=3306;Database=SmartLMS;User=root;Password=${DB_PASSWORD};SslMode=None;Connection Timeout=300;Command Timeout=300;
      - Redis__ConnectionString=YOUR_VPS_IP:6379,password=YOUR_REDIS_PASSWORD_HERE
    ports:
      - "5384:8080"
    networks:
      - smartlms-worker-net

networks:
  smartlms-worker-net:
    driver: bridge

