version: '3.4'

services:
  smartlms-community:
    image: smartlms-community:latest
    build:
      context: .
      dockerfile: SmartLMS.Community/SmartLMS.Community/Dockerfile
    ports:
      - "5182:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=YOUR_VPS_IP;Database=SmartLMS;User=root;Password=YOUR_DB_PASSWORD;
    restart: always


