services:
  backend:
    image: ghcr.io/jacksama11223/asp.net-app/smartlms-backend:latest
    restart: always
    mem_limit: 250m
    deploy:
      replicas: 3
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      # ✅ Kết nối về VPS-A (Thay IP_VPS_A bằng 141.253.114.218)
      - ConnectionStrings__DefaultConnection=Server=141.253.114.218;Port=3306;Database=SmartLMS;User=root;Password=YourStrongPassword123!;SslMode=None;Maximum Pool Size=100;Connection Timeout=300;Command Timeout=300;
      - Redis__ConnectionString=141.253.114.218:6379,password=YOUR_REDIS_PASSWORD_HERE
      - COMPlus_gcServer=0
      - DOTNET_GCConserveMemory=9
      - DOTNET_GCHeapHardLimitPercent=75
    ports:
      - "5381-5383:8080"
    networks:
      - smartlms-worker-net

  frontend-community:
    image: ghcr.io/jacksama11223/asp.net-app/smartlms-frontend:latest
    container_name: smartlms-frontend-community
    restart: always
    mem_limit: 30m
    ports:
      - "5182:80"
    networks:
      - smartlms-worker-net

  community:
    image: ghcr.io/jacksama11223/asp.net-app/smartlms-community:latest
    restart: always
    mem_limit: 200m
    deploy:
      replicas: 1
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=141.253.114.218;Port=3306;Database=SmartLMS;User=root;Password=YourStrongPassword123!;SslMode=None;Connection Timeout=300;Command Timeout=300;
      - Redis__ConnectionString=141.253.114.218:6379,password=YOUR_REDIS_PASSWORD_HERE
    ports:
      - "5384:8080"
    networks:
      - smartlms-worker-net

networks:
  smartlms-worker-net:
    driver: bridge
