events { worker_connections 1024; }

http {
    upstream smartlms_backend {
        # Thuật toán Least Connections (Ưu tiên server đang rảnh)
        least_conn; 
        
        # VPS-A (Local trong mạng Docker của VPS-A)
        server backend:8080; 
        
        # VPS-B (IP công cộng của Server thứ 2)
        # Thay thế IP_VPS_B bằng IP thực tế của server thứ 2
        server 145.241.160.156:5181; 
    }

    server {
        listen 80;

        location /api/ {
            proxy_pass http://smartlms_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Giao diện Frontend (Phục vụ trực tiếp từ VPS-A)
        location / {
            proxy_pass http://frontend:80;
            proxy_set_header Host $host;
        }
    }
}
