<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SmartLMS.Data\SmartLMS.Data.csproj" />
    <ProjectReference Include="..\SmartLMS.Models\SmartLMS.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.3.36" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.22.2" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="DinkToPdf" Version="1.0.8" />
    <PackageReference Include="EPPlus" Version="8.5.1" />
    <PackageReference Include="Hangfire.Core" Version="1.8.23" />
    <PackageReference Include="MailKit" Version="4.16.0" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.2.9" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="4.5.0" />
    <PackageReference Include="MySqlConnector" Version="2.3.7" />
    <PackageReference Include="Dapper" Version="2.1.72" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Microsoft.ML" Version="5.0.0" />
    <PackageReference Include="QRCoder" Version="1.8.0" />
    <PackageReference Include="RabbitMQ.Client" Version="6.8.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
